FROM debian:buster

RUN apt-get update && \
  apt-get install -y bc bison build-essential cpio device-tree-compiler \
    dosfstools flex gcc-aarch64-linux-gnu gcc-arm-none-eabi git jq kmod \
    libfdt-dev libpython-dev libpython3-dev lzop mtools parted python python3 \
    rsync sudo
