FROM debian:buster

RUN apt-get update && \
  apt-get install -y bc bison build-essential device-tree-compiler flex gcc-aarch64-linux-gnu gcc-arm-none-eabi git libfdt-dev libpython-dev lzop python sudo
