FROM debian:buster

RUN apt-get update && \
  apt-get install -y bc bison build-essential cpio device-tree-compiler flex gcc-aarch64-linux-gnu gcc-arm-none-eabi git jq kmod libfdt-dev libpython-dev lzop python rsync sudo
