ARG CODENAME

FROM debian:$CODENAME

RUN apt-get update \
  && apt-get install -y \
    build-essential \
    cmake \
    devscripts \
    git \
    libasound2-dev \
    libfontconfig1-dev \
    libgles2-mesa-dev \
    libglu1-mesa-dev \
    libpcap-dev \
    libsdl2-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libssl-dev \
    libtinyxml-dev \
    libvorbis-dev \
    libvulkan-dev \
    mesa-common-dev \
    python2.7 \
    python3 \
    qtchooser \
    vim-common \
    zlib1g-dev
