name: build

on:
  push:
    branches:
    - master

jobs:   
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
        - name: kodibuilder
          release: bookworm
          platforms: linux/arm64,linux/arm/v7
        - name: ffmpegbuilder
          release: bookworm
          platforms: linux/arm64,linux/arm/v7
        - name: aarch64-linux-crossbuilder
          platforms: linux/amd64
          release: bookworm
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.name }}
        file: ${{ matrix.name }}/Dockerfile
        platforms: ${{ matrix.platforms }}
        push: true
        tags: ghcr.io/sigmaris/${{ matrix.name }}:${{ matrix.release }}
