name: build

on:
  push:
    branches:
    - master

jobs:   
  build:
    strategy:
      matrix:
        name: [kodibuilder, ffmpegbuilder, aarch64-linux-crossbuilder]
        release: [bookworm, trixie]
        include:
        - name: kodibuilder
          platforms: linux/arm64,linux/arm/v7
        - name: ffmpegbuilder
          platforms: linux/arm64,linux/arm/v7
        - name: aarch64-linux-crossbuilder
          platforms: linux/amd64
      fail-fast: false
    runs-on: ubuntu-24.04${{ contains(matrix.platforms, 'linux/arm') && '-arm' || '' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.name }}
        build-args: |
          RELEASE=${{ matrix.release }}
        platforms: ${{ matrix.platforms }}
        push: true
        tags: ghcr.io/sigmaris/${{ matrix.name }}:${{ matrix.release }}
